### ISSUE TITLE
Installation auf einem Raspian Stretch nicht möglich

### ISSUE THREAD

**Issue by NCC1701M** [bablokb/pi-wsa#1]
Die installation des v4l2rstpservers auf einem Raspian Stretch system schlägt fehl, da das liblog4cpp5 Paket nicht installiert ist. Dieses Paket lässt sich jedoch nicht installieren. Laut apt-get ist liblog4cpp5v5 installiert. Dies scheint aber nicht kompatibel mit v4l2 zu sein.

Welche Raspian Version wurde verwendet?

**Comment by bablokb** [comment]
Ich hatte Raspbian Jessie Lite auf einem Pi1 verwendet. Außerdem läuft es erfolgreich auf Jessie Lite mit Pi-Zero-W.
